### ISSUE TITLE
Create an AI Voice Assistant with GPT4ALL for WINDOWS user

### ISSUE THREAD

**Issue by dpenra** [Ai-Austin/GPT4ALL-Voice-Assistant#7]
Please make a video tutorial specifically designed for the Windows platform, ensuring that the instructions are easy for layman to comprehend

**Comment by Ai-Austin** [comment]
Unless someone is paying me to do so, I will stick to my own operating preference. Anyone who wishes to write backend code for Windows, is choosing to write code for an operating system that is less friendly to backend developers. I started learning Python on Windows, it was a terrible mistake that made me feel like I wasn't cut out for coding, but really the operating system just has so many unique errors in your code that results in any wise developer switching to a UNIX operating system for Python development, like Python was originally created for. That is why it is so difficult for you to debug your own code and want me to code on Windows for you. Best of luck, whatever path you take, learning to code.

**Comment by dpenra** [comment]
Not everyone on this planet is a developer, and neither am I. The majority of individuals worldwide do not utilize Linux-based operating systems unless they are professionals. I, like many others, use Windows as my primary operating system. I'm not suggesting that you should switch the operating system for my sake, but I kindly request you to create a video about your project. This way, users of Windows, including myself, can also have the opportunity to explore and experience your project. 
This could potentially boost your YouTube views among users on the Windows platform. In the upcoming days, users might develop one-click installation methods for your project on Windows, further expanding its accessibility. In the meantime, you have a fantastic opportunity to broaden your reach and grow.

**Comment by MrSnoozles** [comment]
@dpenra Have you tried installing WSL2 an running it from there? That way you can have a complete linux (minus a GUI) in Windows.

**Comment by Ai-Austin** [comment]
Github is for developers and my YouTube tutorials are as well.. I am not trying to help people code, that don't care to learn to code. I stopped using Windows 5 years ago. So I do my best to give people advice that are not willing to think for themselves or debug the code they are attempting to "develop". But as someone who uses my right to select the ideal operating for development, I don't ever care to go pull out out a windows computer and do the same process again on a less friendly operating system. 
If you need ME to develop or teach on Windows, I need to be payed. I am not using something I hate, for no benefit of my own. Thanks for the suggestions. 
You are absolutely welcome to ask windows specific questions on my Github and Discord. But expect for 99% of issues my honest answer is: I don't know.

**Comment by Ai-Austin** [comment]
There is this huge multi billion dollar industry called the software industry. People who do not want to develop their own programs, will need to be consumers of us developers products, in order to dictate the future of said product. Without financial incentive, I would not expect developers with a quarter million dollar a year skill to change their ways, to make it more convenient. Developers have their preferences, mine is to not touch Windows, only a high enough price tag will make it worth changing.

**Comment by dpenra** [comment]
Do as your wish.....
