### ISSUE TITLE
gpt4all-falcon model is changed from bin file to .gguf model

### ISSUE THREAD

**Issue by sudharsan-007** [Ai-Austin/GPT4ALL-Voice-Assistant#9]
Downloading the latest model from GPT4All now comes with a different file structure. 

gpt4all-falcon-newbpe-q4_0.gguf

![image](https://github.com/Ai-Austin/GPT4ALL-Voice-Assistant/assets/55453134/8e9645f8-cb97-43a3-9dc2-7503d84b7abb)

**Comment by Ai-Austin** [comment]
Yes. When you use a different version of a Python library, there is potential for changes needed in your code. If you wish to use the newer version of GPT4ALL, put the path to the new file type. As that is your new model file, you need to give your program the path to the file with a different type.
